import { type LoaderFunctionArgs } from "@remix-run/node";
import PDFDocument from "pdfkit";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const url = new URL(request.url);
  const estimate = url.searchParams.get("estimate");
  const description = url.searchParams.get("description");

  if (!estimate) {
    return new Response("Missing estimate data", { status: 400 });
  }

  // Create PDF document
  const doc = new PDFDocument({
    size: "LETTER",
    margins: {
      top: 50,
      bottom: 50,
      left: 50,
      right: 50,
    },
  });

  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  const pdfPromise = new Promise<Buffer>((resolve) => {
    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });
  });

  // Header with branding
  doc
    .fontSize(24)
    .fillColor("#2563eb")
    .text("HandyBid AI", { align: "left" });

  doc
    .fontSize(10)
    .fillColor("#64748b")
    .text("Professional Bid Estimate", { align: "left" });

  doc.moveDown();

  // Date
  doc
    .fontSize(10)
    .fillColor("#475569")
    .text(`Date: ${new Date().toLocaleDateString()}`, { align: "right" });

  doc.moveDown(2);

  // Job Description Section
  if (description) {
    doc
      .fontSize(12)
      .fillColor("#1e293b")
      .text("Job Description:", { underline: true });

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#475569")
      .text(decodeURIComponent(description), {
        align: "left",
        width: 500,
      });

    doc.moveDown(2);
  }

  // Estimate Section
  doc
    .fontSize(12)
    .fillColor("#1e293b")
    .text("Detailed Estimate:", { underline: true });

  doc.moveDown(0.5);

  // Parse and format the estimate
  const estimateText = decodeURIComponent(estimate);
  const lines = estimateText.split("\n");

  for (const line of lines) {
    if (line.trim().length === 0) {
      doc.moveDown(0.5);
      continue;
    }

    // Check if line is a header (starts with ##)
    if (line.startsWith("##")) {
      doc.moveDown(0.5);
      doc
        .fontSize(11)
        .fillColor("#1e293b")
        .text(line.replace(/^##\s*/, ""), { underline: true });
      doc.moveDown(0.3);
    }
    // Check if line is bold (**text**)
    else if (line.includes("**")) {
      const parts = line.split("**");
      let x = doc.x;
      for (let i = 0; i < parts.length; i++) {
        if (i % 2 === 1) {
          // Bold text
          doc.font("Helvetica-Bold").fontSize(10).fillColor("#1e293b");
        } else {
          // Regular text
          doc.font("Helvetica").fontSize(10).fillColor("#475569");
        }
        doc.text(parts[i], x, doc.y, { continued: i < parts.length - 1 });
        x += doc.widthOfString(parts[i]);
      }
      doc.text(""); // New line
    }
    // Check if line starts with a bullet or dash
    else if (line.trim().startsWith("-") || line.trim().startsWith("•")) {
      doc
        .fontSize(10)
        .fillColor("#475569")
        .text(`  ${line.trim()}`, { indent: 10 });
    }
    // Regular text
    else {
      doc.fontSize(10).fillColor("#475569").text(line.trim());
    }
  }

  // Footer
  doc.moveDown(3);
  doc
    .fontSize(8)
    .fillColor("#94a3b8")
    .text("Generated by HandyBid AI - Powered by Claude", {
      align: "center",
    });

  doc
    .fontSize(8)
    .fillColor("#cbd5e1")
    .text("This is an estimate. Final costs may vary.", { align: "center" });

  doc.end();

  const pdfBuffer = await pdfPromise;

  return new Response(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="bid-estimate-${Date.now()}.pdf"`,
    },
  });
};
